name: Update Combined INFO

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run script
        env:
           GITHUB_TOKEN: ${{ secrets.COMBINED_INFO_CREATOR }}
        run: |
          pip install PyGithub
          python combined_info_creator.py

